Vagrant.configure("2") do |config|
  vm_count = 3
  (1..vm_count).each do |i|
    config.vm.define "master#{i}" do |master|
      master.vm.box = "ubuntu/focal64"
      master.vm.hostname = "master#{i}"
      master.vm.network "private_network", ip: "192.168.56.10#{i}"
      master.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y nginx
      SHELL
      master.vm.provider "virtualbox" do |vb|
        vb.name = "master#{i}"
        vb.memory = 512
        vb.cpus = 1
      end
    end
  end
end