Vagrant.configure("2") do |config|
  vm_count = 3

  (1..vm_count).each do |i|
    config.vm.define "web#{i}" do |web|
      web.vm.box = "ubuntu/focal64"
      web.vm.hostname = "web#{i}"

      web.vm.network "private_network", ip: "192.168.56.10#{i}"

      web.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y nginx
      SHELL

      web.vm.provider "virtualbox" do |vb|
        vb.name = "web#{i}"
        vb.memory = 512
        vb.cpus = 1
      end
    end
  end
end