Vagrant.configure("2") do |config|
  config.vm.define "ubuntu-vm" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.hostname = "ubuntu-vm"
    ubuntu.vm.network "private_network", ip: "192.168.56.104"
    ubuntu.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y curl
    SHELL
  end

  config.vm.define "centos-vm" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "centos-vm"
    centos.vm.network "private_network", ip: "192.168.56.105"
    centos.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      sudo yum install -y curl
    SHELL
  end
end